#----------------------------------------------------------------------------

all:
	make -C lib
	make -C sigma0
	make -C root
	make -C io
	make -C l4ka-pingpong

clean:
	make -C lib clean
	make -C sigma0 clean
	make -C root clean
	make -C io clean
	make -C l4ka-pingpong clean

#----------------------------------------------------------------------------
